### PR TITLE
adding a section around a base domain standard

### PR DESCRIPTION
**Pull request by gbinal**
@jcastle, @nvembar - game to take a look and consider this?  Also, who else would you like to weigh in on it?  

We've [discussed it before](https://github.com/GSA/api-standards/blob/master/api-design/overview.md) and [are making progress](https://github.com/GSA/api-standards/blob/master/api-design/README.md) in implementing it, but I think it'd help to consider adding it to GSA's API standards going forward.

### CODE REVIEW

**Comment by gbinal** [comment]
@rdgsa, @nvembar - barring objections to this, I'd like to go ahead and merge it in.  It'll be really helpful to have this in the standards and in the long run, we'll be glad we did it.

**Comment by nvembar** [comment]
@gbinal Sorry, yes, this makes sense - go ahead and merge.

**Comment by rdgsa** [comment]
@gbinal I think there are some tweaks we can make to the API Endpoints section above it, to clarify how the (path) and base domain work together. But @nvembar gave the thumbs up so I think you're good to merge this and then we can tweak the above section later.

**Comment by gbinal** [comment]
Belatedly returning to this.  Merging now....

**Pull request merged**
