### PR TITLE
2018 updates to API Standards

### PR DESCRIPTION
**Pull request by Ryandaydev**
This is the pull request to merge the 2018 updates.

Please add comments to this pull request, and the team will address as we go.

Major updates:
- Addition of Mandatory Items section.

### CODE REVIEW

**Comment by MickinSahni** [comment]
Thanks for sharing, Ryan. Is it worthwhile to include suggestions of the sorts of information that should be passed in a particular request component i.e. headers vs. body? I may have missed this elsewhere so apologies in case it's a dupe.

**Comment by Ryandaydev** [comment]
We need to clarify the mandatory item "API endpoint design" and decide which parts are truly mandatory.

**Comment by Ryandaydev** [comment]
Suggest we add a section with definitions:

- Non Public APIs - Available only to GSA applications and users.
- Public APIs - Available to non-GSA users. Examples include the general public, other agencies, or companies. 

The reason that I am not proposing a separate category of "Partner APIs" is because we are proposing that all APIs implement key management and in essence become "partner APIs".

**Comment by Ryandaydev** [comment]
Business_Function: can we propose a list of these?

**Comment by Ryandaydev** [comment]
Endpoint design & API.GSA.GOV - -make clear within one year don't have to move all existing customers over.

**Comment by Ryandaydev** [comment]
API.GSA.GOV section -- also make allowance for api.usa.gov if that is a valid alternative.

**Comment by Ryandaydev** [comment]
Resolves #34
Resolves #39 
Resolves #26

**Comment by Ryandaydev** [comment]
> Thanks for sharing, Ryan. Is it worthwhile to include suggestions of the sorts of information that should be passed in a particular request component i.e. headers vs. body? I may have missed this elsewhere so apologies in case it's a dupe.
@MickinSahni Do you have best practices doc to reference or any specific recommendations? If we don't get it into this round of updates, we can add in the next major update that will come with API security.

**Comment by MickinSahni** [comment]
> > Thanks for sharing, Ryan. Is it worthwhile to include suggestions of the sorts of information that should be passed in a particular request component i.e. headers vs. body? I may have missed this elsewhere so apologies in case it's a dupe.
> 
> @MickinSahni Do you have best practices doc to reference or any specific recommendations? If we don't get it into this round of updates, we can add in the next major update that will come with API security.

@Ryandaydev My go-to would be a reference source like OWASP. Here's a section of their REST Security Cheat Sheet that's helpful: https://www.owasp.org/index.php/REST_Security_Cheat_Sheet#Sensitive_information_in_HTTP_requests

**Comment by Ryandaydev** [comment]
>>My go-to would be a reference source like OWASP. Here's a section of their REST Security Cheat Sheet that's helpful: https://www.owasp.org/index.php/REST_Security_Cheat_Sheet#Sensitive_information_in_HTTP_requests

Hey, that is a great reference, thanks! I will be sure this info gets included in the work we're doing on the API security guide, and then it will flow into these standards when those are finalized.

**Pull request merged**
